spring:
  redis:
    host: 101.200.193.180 # Redis 服务器地址
    database: 0 # Redis 数据库索引（默认为 0）
    port: 9521 # Redis 服务器连接端口
    password: zhishe # Redis 服务器连接密码（默认为空），使用启动参数覆盖此设置
    timeout: 300ms # 连接超时时间（毫秒）
  datasource:
    url: jdbc:mysql://101.200.193.180:3306/zhishedb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mysqldb # 使用启动参数覆盖此设置
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: # 需要重新设置
        login-password: # 需要重新设置
