server:
  port: 8888

spring:
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

redis:
  database: zhishe
  key:
    user: 'sys:user'
    post:
      liked: 'post:liked'
      liked-count: 'post:liked:count'
  expire:
    common: 86400 # 24 小时

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization # JWT 存储的请求头
  secret: cms-secret # JWT 加解密使用的密钥
  expiration: 900 # JWT 的超期限时间 (60 * 15 * 1 * 1)
  tokenHead: Bearer  # JWT 负载中拿到开头

# 返回给前端的角色字符串
role:
  admin: admin
  student: student

secure:
  ignored:
    urls: # 安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /auth/login
      - /auth/register
      - /auth/info
      - /auth/logout
      - /users/answer
      - /users/question
      - /users/password
      - /home/**
      - /clubs/**
      - /forum/**
      - /roles/**
      - /files/images/**

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.macro.mall: debug
#  file: demo_log.log #配置日志生成路径
#  path: /var/logs #配置日志文件名称

storage:
  path:
    str:
      image: images
      file: files
  location:
    images: /cms-core/src/main/resources/static/upload-dir/images
    files: /cms-core/src/main/resources/static/upload-dir/files
