server:
  port: 8888

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://101.200.193.180:3306/zhishedb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: # 使用启动参数覆盖此设置
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

redis:
  database: zhishe
  key:
    user: 'sys:user'
    # resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24 小时

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization # JWT 存储的请求头
  secret: cms-secret # JWT 加解密使用的密钥
  expiration: 900 # JWT 的超期限时间 (60 * 15 * 1 * 1)
  tokenHead: Bearer  # JWT 负载中拿到开头

secure:
  ignored:
    urls: # 安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /auth/login
      - /auth/register
      - /auth/info
      - /auth/logout
      - /users/answer
      - /users/question
      - /users/password
      - /home/**
      - /test/**
      - /clubs/recommended
      - /forum/**

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.macro.mall: debug
#  file: demo_log.log #配置日志生成路径
#  path: /var/logs #配置日志文件名称
